<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>nopCommerce</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-05-21T04:41:07</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0fc50604-5022-4223-9a8d-6164c26242ad</testSuiteGuid>
   <testCaseLink>
      <guid>8862f420-c7f0-4885-ab8b-48f5c467dd1d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify-Registration</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7356c6eb-f7ed-4d90-9f4e-a4fc4c5fa1bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e42550cd-eb38-459d-8638-f903bead6053</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1df0fe60-d999-4796-a564-2f49fdecca60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aeb7bc04-845e-496c-96ca-560b04da0ce3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84917026-cdc0-4d60-86bd-b410c0b4db92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe48b41f-e73e-4570-b74e-5cd306199f0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53169467-36fd-4e12-b7bd-161ca4da7f4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e17f56c8-1642-4873-9e57-ec90fb700702</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12b84c87-ab85-4d5d-8e3b-97dd471a3e88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5914612b-3437-4052-9420-dc16e8404332</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify-Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb8add7f-3752-4922-82f5-c2388199f982</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56196de1-e0b6-4b41-bb95-3b9150523bd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify-AddLumiaToCart</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c61222b-02b9-4d15-acd2-9cfe836eeef6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b67380f0-32c9-4c8b-a6c8-33173e7e33b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify-FlowerGirlBracelet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a8e62f2-0997-4369-814c-ade7eb4330ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>152e62be-2a0f-441e-a5d7-bc0ade28556e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify-RemoveLumiaFromCart</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f6d76364-8bb1-4624-b44a-b4bc4d32a945</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify-CheckOut</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7993a3a2-80c4-42b3-892e-dd6777d9bd02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a0d4bc5-eaf4-4c50-a486-c9a1fc59a131</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61b6b966-664a-4c7e-abeb-aa3f48fdd851</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9af0e5e-4083-4592-86fa-cf219d8aacfd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5c427b8-79fe-4ff0-a47f-ff7e5d8d8e4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b595388-d97b-4fc4-b8aa-f951e5f5273d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2325bdb-f626-4b26-8fe7-15a16a7436a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd4935c4-8872-4da4-980d-ffc1dc4d2f08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>081c7938-41b8-4af0-843f-33582e4c8328</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>867ec0e3-8119-45f2-9621-94e2658b624e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76f7fdfe-9a8e-41ef-9f47-ac238e9e18cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e362954b-9f6a-44cf-8cc8-ce42cfcbe033</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify-Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
